### ISSUE TITLE
Cannot run rpm run build - reporting incorrect Rust version?

### ISSUE THREAD

**Issue by garethcurtis** [ExtropyIO/SolanaBootcamp#23]
Hi,

Can anyone offer any help/advice on the below please?

`garethcurtis@Gareths-iMac SolanaBootcamp % npm run build

> solana-course@0.0.1 build
> cargo build-bpf --workspace --manifest-path=./examples_baremetal/Cargo.toml

error: package `solana-program v2.0.5` cannot be built because it requires rustc 1.75.0 or newer, while the currently active rustc version is 1.68.0-dev
Either upgrade to rustc 1.75.0 or newer, or use
cargo update -p solana-program@2.0.5 --precise ver
where `ver` is the latest version of `solana-program` supporting rustc 1.68.0-dev
garethcurtis@Gareths-iMac SolanaBootcamp % rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
garethcurtis@Gareths-iMac SolanaBootcamp % `

Why does it say active rustc version is 1.68.0-dev? Mine is 1.82 and I wouldn't install any dev version! : D

Any assistance much appreciated.

Thanks.

**Comment by foxreymann** [comment]
@garethcurtis How did you fix it?

**Comment by garethcurtis** [comment]
Hi - I didn't. I asked for help several times; Zoom, here and Slido but got no response. So I gave up...

**Comment by foxreymann** [comment]
because I as mention at the beginning of every session: "Between lessons you can ask on Technical Questions channel on Discord." and "To get your technical questions answered please ask on Slido, not on Zoom Chat.". If you've asked this question on Slido I've surely asked you to post on Discord.

**Comment by garethcurtis** [comment]
Apologies - I seem to have misunderstood then.
